services:
  - type: web
    name: storyrealm
    env: node
    rootDir: storyrealm
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLAUDE_API_KEY
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
